global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nestjs-api-instances'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'api-1:3000'
        - 'api-2:3000'
        - 'api-3:3000'
        labels:
          service: 'api'

  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'loadbalancer'
